import { Dish } from './dishes.service';

export const GENERAL_DISHES: Dish[] = [
  { name: 'Slaw', hungerValue: 25, sanityValue: 10, healthValue: 20 },
  { name: 'Lotus Chips', hungerValue: 12.5, sanityValue: 50, healthValue: 8 },
  { name: 'Poi', hungerValue: 62.5, sanityValue: 10, healthValue: 30 },
  { name: 'Cucumber Salad', hungerValue: 25, sanityValue: 15, healthValue: 10 },
  { name: 'Watercress Soup', hungerValue: 37.5, sanityValue: 5, healthValue: 20 },
  { name: 'Symphony of the Gears', hungerValue: 150, sanityValue: 150, healthValue: 135 },
  { name: 'Deadly Feast', hungerValue: 150, sanityValue: -300, healthValue: -100 },
  { name: "Tigela di' Merde", hungerValue: 0, sanityValue: 0, healthValue: 0 },
  { name: 'Kitty Snack', hungerValue: 25, sanityValue: 15, healthValue: 20 },
  { name: 'Kitty Kat Snack', hungerValue: 15, sanityValue: 15, healthValue: 60 },
  { name: 'Bowl of Popcorn', hungerValue: 75, sanityValue: 33, healthValue: 5 },
  { name: 'Fig Juice', hungerValue: 15, sanityValue: 50, healthValue: 0 },
  { name: 'Coconut Water', hungerValue: 0, sanityValue: 0, healthValue: 20 },
  { name: 'Eyespaghetti', hungerValue: 150, sanityValue: -150, healthValue: 150 },
  { name: 'Soul Stew', hungerValue: 62.5, sanityValue: -10, healthValue: 10 },
  { name: 'Fortune Cookie', hungerValue: 20, sanityValue: 5, healthValue: 3 },
  { name: 'Cornocupia', hungerValue: 75, sanityValue: 25, healthValue: 12 },
  { name: 'Milk Box', hungerValue: 0, sanityValue: 5, healthValue: 25 },
  { name: 'Honey Jar', hungerValue: 45, sanityValue: 5, healthValue: 30 },
  { name: 'Cup of Water', hungerValue: 1, sanityValue: 1, healthValue: 1 },
  { name: 'Crab Artichoke', hungerValue: 12.5, sanityValue: 60, healthValue: 40 },
  { name: 'Cheese', hungerValue: 25, sanityValue: 5, healthValue: 10 },
  { name: 'White Cheese', hungerValue: 25, sanityValue: 20, healthValue: 15 },
  { name: 'Koalefant Cheese', hungerValue: 25, sanityValue: 5, healthValue: 20 },
  { name: 'Noxious Froggle Bunwich', hungerValue: 62.5, sanityValue: 10, healthValue: -20 },
  { name: 'Pepper Rolls', hungerValue: 32.5, sanityValue: -15, healthValue: 40 },
  { name: 'Chocolate', hungerValue: 12.5, sanityValue: 33, healthValue: -5 },
  { name: 'White Chocolate', hungerValue: 33, sanityValue: 12.5, healthValue: -5 },
  { name: 'Tricolor Dango', hungerValue: 12.5, sanityValue: 5, healthValue: 30 },
  { name: 'French Fries', hungerValue: 32.5, sanityValue: 10, healthValue: 30 },
  { name: 'Onion Rings', hungerValue: 25, sanityValue: 20, healthValue: 15 },
  { name: 'Donuts', hungerValue: 50, sanityValue: 10, healthValue: -3 },
  { name: 'Chocolate Donuts', hungerValue: 55, sanityValue: 40, healthValue: -5 },
  { name: 'White Chocolate Donuts', hungerValue: 75, sanityValue: 15, healthValue: -5 },
  { name: 'Gummy Beargers', hungerValue: 30, sanityValue: -5, healthValue: 5 },
  { name: 'Pretzel', hungerValue: 60, sanityValue: 15, healthValue: 40 },
  { name: 'Elote en Vaso', hungerValue: 50, sanityValue: 50, healthValue: 50 },
  { name: 'Cotton Candy', hungerValue: 12.5, sanityValue: 33, healthValue: -5 },
  { name: 'Roasted Hazelnuts', hungerValue: 25, sanityValue: 10, healthValue: 10 },
  { name: 'Monster Muffin', hungerValue: 50, sanityValue: -15, healthValue: -10 },
  { name: 'Pink Cake', hungerValue: 62.5, sanityValue: 20, healthValue: 5 },
  { name: 'Potato Chips', hungerValue: 62.5, sanityValue: 5, healthValue: 40 },
  { name: 'Bread', hungerValue: 12.5, sanityValue: 5, healthValue: 0 },
  { name: 'Hot Hound', hungerValue: 32.5, sanityValue: 10, healthValue: 60 },
  { name: 'Milkshake', hungerValue: 12.5, sanityValue: 30, healthValue: 30 },
  { name: 'Banana Pudding', hungerValue: 12.5, sanityValue: 50, healthValue: 20 },
  { name: 'Seafoam Pudding', hungerValue: 150, sanityValue: 5, healthValue: 60 },
  { name: 'Lollipop', hungerValue: 12.5, sanityValue: 15, healthValue: -3 },
  { name: 'Radish Salad', hungerValue: 62.5, sanityValue: 5, healthValue: 15 },
  { name: 'Pumpkin Soup', hungerValue: 100, sanityValue: 33, healthValue: 40 },
  { name: 'Algae Soup', hungerValue: 75, sanityValue: 25, healthValue: 10 },
  { name: 'Parsnip Soup', hungerValue: 32.5, sanityValue: 5, healthValue: 15 },
  { name: 'Living Sandwich', hungerValue: 40, sanityValue: -5, healthValue: 10 },
  { name: 'Moon Shroom Sofrito', hungerValue: 18.75, sanityValue: 0, healthValue: 25 },
  { name: 'Lavender Wobster Soup', hungerValue: 62.5, sanityValue: -5, healthValue: -60 },
  { name: 'Wobster Monster', hungerValue: 37.5, sanityValue: -20, healthValue: -60 },
  { name: 'Durian Split', hungerValue: 32.5, sanityValue: -15, healthValue: -5 },
  { name: 'Durian Soup', hungerValue: 37.5, sanityValue: 0, healthValue: -15 },
  { name: 'Meated Durians', hungerValue: 37.5, sanityValue: -5, healthValue: -20 },
  { name: 'Turkey Durian', hungerValue: 45, sanityValue: -30, healthValue: -10 },
  { name: 'Arachnid Gateau', hungerValue: 37.5, sanityValue: -20, healthValue: -20 },
  { name: 'Sugar Bombs', hungerValue: 20, sanityValue: 15, healthValue: 5 },
  { name: 'Berries Basket', hungerValue: 18.25, sanityValue: 5, healthValue: 12 },
  { name: 'Onigiris', hungerValue: 20, sanityValue: 8, healthValue: 8 },
  { name: 'Omurice', hungerValue: 32.5, sanityValue: 10, healthValue: 30 },
  { name: 'Paella', hungerValue: 50, sanityValue: 10, healthValue: 20 },
  { name: 'Tropical Pizza', hungerValue: 75, sanityValue: 15, healthValue: 60 },
  { name: 'Piña Colada', hungerValue: 25, sanityValue: 10, healthValue: 25 },
  { name: 'Mate', hungerValue: 12.5, sanityValue: 10, healthValue: 5 },
  { name: 'Gummy Worms', hungerValue: 25, sanityValue: -5, healthValue: 10 },
  { name: "S'mores", hungerValue: 65, sanityValue: 65, healthValue: 15 },
  { name: 'Ants On a Living Log', hungerValue: 25, sanityValue: 15, healthValue: 15 },
  { name: 'Moon Muffin', hungerValue: 37.5, sanityValue: 20, healthValue: 5 },
  { name: 'Sugar Muffin', hungerValue: 18.75, sanityValue: 20, healthValue: 20 },
  { name: 'Eel Tacos', hungerValue: 37.5, sanityValue: 20, healthValue: 5 },
  { name: 'Meat-Toast Waltz', hungerValue: 37.5, sanityValue: 5, healthValue: 30 },
  { name: 'Complete Breakfast', hungerValue: 150, sanityValue: 5, healthValue: 60 },
  { name: 'Dumplings', hungerValue: 25, sanityValue: 10, healthValue: 15 },
  { name: 'Chicken Croquet', hungerValue: 32.5, sanityValue: 0, healthValue: 15 },
  { name: 'Crab King Boil', hungerValue: 62.5, sanityValue: 33, healthValue: 40 },
  { name: 'Pie-Napple', hungerValue: 25, sanityValue: 5, healthValue: 40 },
  { name: 'Avocado Toast', hungerValue: 37.5, sanityValue: 5, healthValue: 5 },
  { name: 'Rice Pudding', hungerValue: 15, sanityValue: 33, healthValue: 5 },
  { name: 'Shark Nigiri', hungerValue: 40, sanityValue: -10, healthValue: 20 },
  { name: 'Breaded Wobster', hungerValue: 50, sanityValue: 10, healthValue: 60 },
  { name: 'Purrito', hungerValue: 62.5, sanityValue: -15, healthValue: 20 },
  { name: 'Horchata', hungerValue: 20, sanityValue: 5, healthValue: 40 },
  { name: 'Wobster Cocktail', hungerValue: 32.5, sanityValue: 60, healthValue: 20 },
  { name: 'Bubblegranate', hungerValue: 12.5, sanityValue: 10, healthValue: 25 },
  { name: 'Piegranate', hungerValue: 32.5, sanityValue: 20, healthValue: 40 },
  { name: 'Pineapple Cake', hungerValue: 25, sanityValue: 40, healthValue: 20 },
  { name: 'Meat Pasty', hungerValue: 62.5, sanityValue: 5, healthValue: 20 },
  { name: 'Cheese Pasty', hungerValue: 37.5, sanityValue: 33, healthValue: 40 },
  { name: 'Brigadier', hungerValue: 32.5, sanityValue: 50, healthValue: 25 },
  { name: 'Lasagna', hungerValue: 37.5, sanityValue: 30, healthValue: 30 },
  { name: 'FLT', hungerValue: 32.5, sanityValue: 33, healthValue: 15 },
  { name: 'Rice and Beans', hungerValue: 62.5, sanityValue: 20, healthValue: 5 },
  { name: 'Jawsbreaker', hungerValue: 12.5, sanityValue: 33, healthValue: -30 }
];
