import { Dish } from './dish.service';

export const HAMLET_DISHES: Dish[] = [
  { name: 'Feijoada', hungerValue: 75, sanityValue: 15, healthValue: 20 },
  { name: 'Gummy Cake', hungerValue: 150, sanityValue: -5, healthValue: -3 },
  { name: 'Hard Shell Tacos', hungerValue: 37.5, sanityValue: 5, healthValue: 20 },
  { name: 'Iced Tea', hungerValue: 12.5, sanityValue: 33, healthValue: 25 },
  { name: 'Tea', hungerValue: 12.5, sanityValue: 33, healthValue: 25 },
  { name: 'Fire Nettle Rolls', hungerValue: 25, sanityValue: -10, healthValue: 20 },
  { name: 'Meated Fire Nettle', hungerValue: 37.5, sanityValue: -5, healthValue: 20 },
  { name: 'Worm Bone Soup', hungerValue: 80, sanityValue: 20, healthValue: 40 },
  { name: 'Steamed Ham Sandwich', hungerValue: 62.5, sanityValue: 15, healthValue: 30 },
  { name: 'Loaf of Bread', hungerValue: 12.5, sanityValue: 0, healthValue: 3 },
  { name: 'Sweet Potato Chips', hungerValue: 75, sanityValue: 15, healthValue: 25 },
  { name: 'Vegetable Soup', hungerValue: 25, sanityValue: 10, healthValue: 8 },
  { name: 'Jelly Sandwich', hungerValue: 37.5, sanityValue: 15, healthValue: 3 },
  { name: 'Fish Stew', hungerValue: 100, sanityValue: 5, healthValue: 20 },
  { name: 'Turnip Cake', hungerValue: 37.5, sanityValue: 10, healthValue: 20 },
  { name: 'Potato Pancakes', hungerValue: 40, sanityValue: 40, healthValue: 40 },
  { name: 'Potato Soup', hungerValue: 75, sanityValue: 15, healthValue: 60 },
  { name: 'Fishball Skewers', hungerValue: 37.5, sanityValue: 20, healthValue: 25 },
  { name: 'Meat Skewers', hungerValue: 37.5, sanityValue: 5, healthValue: 20 },
  { name: 'Stone Soup', hungerValue: 25, sanityValue: 5, healthValue: -10 },
  { name: 'Croquette', hungerValue: 50, sanityValue: 10, healthValue: 30 },
  { name: 'Roast Vegetables', hungerValue: 40, sanityValue: 20, healthValue: 25 },
  { name: 'Meatloaf', hungerValue: 25, sanityValue: 5, healthValue: 30 },
  { name: 'Carrot Soup', hungerValue: 37.5, sanityValue: 10, healthValue: 10 },
  { name: 'Fish Pie', hungerValue: 62.5, sanityValue: 5, healthValue: 40 },
  { name: 'Fish and Chips', hungerValue: 85, sanityValue: 15, healthValue: 50 },
  { name: 'Meat Pie', hungerValue: 50, sanityValue: 25, healthValue: 3 },
  { name: 'Sliders', hungerValue: 12.5, sanityValue: 25, healthValue: 5 },
  { name: 'Jelly Roll', hungerValue: 25, sanityValue: 15, healthValue: 8 },
  { name: 'Carrot Cake', hungerValue: 37.5, sanityValue: 5, healthValue: 15 },
  { name: 'Garlic Mashed Potatoes', hungerValue: 37.5, sanityValue: 15, healthValue: 30 },
  { name: 'Garlic Bread', hungerValue: 37.5, sanityValue: 5, healthValue: 30 },
  { name: 'Tomato Soup', hungerValue: 50, sanityValue: 15, healthValue: 25 },
  { name: 'Sausage', hungerValue: 37.5, sanityValue: 10, healthValue: 30 },
  { name: 'Candied Fish', hungerValue: 25, sanityValue: 60, healthValue: 5 },
  { name: 'Stuffed Mushroom', hungerValue: 20, sanityValue: 10, healthValue: 15 },
  { name: 'Bruschetta', hungerValue: 62.5, sanityValue: 10, healthValue: 50 },
  { name: 'Hamburger', hungerValue: 80, sanityValue: 5, healthValue: 5 },
  { name: 'Fishburger', hungerValue: 80, sanityValue: 5, healthValue: 20 },
  { name: 'Mushroom Burger', hungerValue: 80, sanityValue: 0, healthValue: 5 },
  { name: 'Fish Steak', hungerValue: 150, sanityValue: 15, healthValue: 15 },
  { name: 'Curry', hungerValue: 75, sanityValue: 15, healthValue: 10 },
  { name: 'Spaghetti and Meatball', hungerValue: 80, sanityValue: 25, healthValue: 8 },
  { name: 'Poached Fish', hungerValue: 25, sanityValue: 25, healthValue: 40 },
  { name: "Shepherd's Pie", hungerValue: 150, sanityValue: 10, healthValue: 20 },
  { name: 'Caramel Candy', hungerValue: 20, sanityValue: 33, healthValue: 0 },
  { name: 'Bread Pudding', hungerValue: 40, sanityValue: 40, healthValue: 15 },
  { name: 'Berry Tart', hungerValue: 20, sanityValue: 15, healthValue: 25 },
  { name: 'Macaroni and Cheese', hungerValue: 37.5, sanityValue: 50, healthValue: 20 },
  { name: 'Bagel and Fish', hungerValue: 75, sanityValue: 50, healthValue: 50 },
  { name: 'Grilled Cheese', hungerValue: 50, sanityValue: 40, healthValue: 60 },
  { name: 'Cream of Mushroom Soup', hungerValue: 50, sanityValue: 25, healthValue: 30 },
  { name: 'Manicotti', hungerValue: 50, sanityValue: 50, healthValue: 8 },
  { name: 'Creamy Fettuccine', hungerValue: 50, sanityValue: 40, healthValue: 20 },
  { name: 'Onion Soup', hungerValue: 75, sanityValue: -5, healthValue: 25 },
  { name: 'Bread Cutlet', hungerValue: 75, sanityValue: 15, healthValue: 30 },
  { name: 'Creamy Fish', hungerValue: 75, sanityValue: 30, healthValue: 40 },
  { name: 'Pot Roast', hungerValue: 150, sanityValue: 5, healthValue: 30 },
  { name: 'Crab Cake', hungerValue: 62.5, sanityValue: 20, healthValue: 60 },
  { name: 'Steak Frites', hungerValue: 100, sanityValue: 5, healthValue: 40 },
  { name: 'Shooter Sandwich', hungerValue: 100, sanityValue: 15, healthValue: 5 },
  { name: 'Bacon Wrapped Meat', hungerValue: 50, sanityValue: 0, healthValue: 10 },
  { name: 'Crab Roll', hungerValue: 75, sanityValue: 25, healthValue: 60 },
  { name: 'Crab Ravioli', hungerValue: 40, sanityValue: 50, healthValue: 60 },
  { name: 'Caramel Cube', hungerValue: 20, sanityValue: 100, healthValue: -10 },
  { name: 'Scone', hungerValue: 37.5, sanityValue: 40, healthValue: 5 },
  { name: 'Cheesecake', hungerValue: 75, sanityValue: 60, healthValue: 20 },
  { name: 'Syrup', hungerValue: 9.375, sanityValue: 0, healthValue: 3 }
];

