import { Dish } from './dish.service';

export const KEG_DISHES: Dish[] = [
  { name: 'Beer', hungerValue: 12.5, sanityValue: -10, healthValue: 5, cookingTime: 1, requirements: '2 Units of Wheat and 1 Unit of Ice.', effects: 'Increases strength.', cookingStation: "keg" },
  { name: 'Pale Ale', hungerValue: 25, sanityValue: -10, healthValue: 15, cookingTime: 2, requirements: '2 Units of Spotty Sprig and 1 Unit of Ice.', effects: 'Increases strength.', cookingStation: "keg" },
  { name: 'Green Tea', hungerValue: 32, sanityValue: 1, healthValue: 12, cookingTime: 1, requirements: '1 Unit of Green Cap, 1 Unit of Orange Piko and 1 Unit of Tea Leaves.', effects: 'Restores sanity over time.', cookingStation: "keg" },
  { name: 'Black Tea', hungerValue: 32, sanityValue: 12, healthValue: 1, cookingTime: 1, requirements: '1 Unit of Red Cap, 1 Unit of Piko and 1 Unit of Tea Leaves.', effects: 'Restores health over time.', cookingStation: "keg" },
  { name: 'Mead', hungerValue: 70, sanityValue: 40, healthValue: -10, cookingTime: 3, requirements: '2 Units of Honey or Syrup and 1 Unit of Ice.', effects: 'Increases defense.', cookingStation: "keg" },
  { name: 'Pirate\'s Rum', hungerValue: 60, sanityValue: -33, healthValue: -15, cookingTime: 2, requirements: '1 Unit of Durian, 1 Unit of Syrup and 1 Unit of Ice.', effects: 'Increases damage to pirates.', cookingStation: "keg" },
  { name: 'Twisted Tequila', hungerValue: 32.5, sanityValue: -30, healthValue: 15, cookingTime: 1, requirements: '1 Unit of Aloe, 1 Unit of Spotty Sprig and 1 Unit of Ice.', effects: 'Twists the spacetime.', cookingStation: "keg" },
  { name: 'Nuka-Cola', hungerValue: 12.5, sanityValue: 60, healthValue: -5, cookingTime: 2, requirements: '1 Unit of Sugar, 1 Unit of Syrup and 1 Unit of Ice.', effects: 'Cools the body.', cookingStation: "keg" },
  { name: 'Nuka-Cola Quantum', hungerValue: 20, sanityValue: 60, healthValue: -10, cookingTime: 3, requirements: '1 Unit of Sugar, 1 Unit of Glow Berry and 1 Unit of Ice.', effects: 'Cools the body and Gives off a healthy glow.', cookingStation: "keg" },
  { name: 'Nukashine', hungerValue: 150, sanityValue: -100, healthValue: 100, cookingTime: 3, requirements: '1 Unit of Nuka-Cola Quantum, 1 Unit of Sugar and 1 Unit of Nightberry.', effects: 'May cause blackouts.', cookingStation: "keg" },
  { name: 'Sake', hungerValue: 32.5, sanityValue: 20, healthValue: -10, cookingTime: 2, requirements: '2 Units of Rice and 1 Unit of Ice.', effects: 'Increases defense.', cookingStation: "keg" },
  { name: 'Mocha', hungerValue: 33, sanityValue: 33, healthValue: -10, cookingTime: 3, requirements: '2 Units of Cooked Coffee Beans and 1 Unit of Chocolate.', effects: 'Warms the body, wards off sleep, speeds the body and decreases hunger loss.', cookingStation: "keg" },
  { name: 'Croak-Cola', hungerValue: 12.5, sanityValue: 80, healthValue: -30, cookingTime: 3, requirements: '1 Unit of Poison Frog Legs, 1 Unit of Sugar and 1 Unit of Ice.', effects: 'Increases damage to amphibians.', cookingStation: "keg" },
  { name: 'Tepache', hungerValue: 12.5, sanityValue: 33, healthValue: 20, cookingTime: 1, requirements: '1 Unit of Halved Pineapple, 1 Unit of Sugar and 1 Unit of Ice.', effects: 'Cools the body.', cookingStation: "keg" },
  { name: 'Enlightened Tequila', hungerValue: 12.5, sanityValue: 100, healthValue: 5, cookingTime: 3, requirements: '1 Unit of Lunar Tree Blossom, 1 Unit of Pure Brilliance and 1 Unit of Ice.', effects: 'Enlightens the mind.', cookingStation: "keg" },
  { name: 'Sneakmosa', hungerValue: 12.5, sanityValue: -100, healthValue: 5, cookingTime: 3, requirements: '1 Unit of Halved Pineapple, 1 Unit of Pure Horror and 1 Unit of Ice.', effects: 'Hides your presence.', cookingStation: "keg" },
  { name: 'Berries Wine', hungerValue: 20, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Berries and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Juicy Berries Wine', hungerValue: 20, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Juicy Berries and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Pomegranate Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Pomegranate and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Dragon Fruit Wine', hungerValue: 20, sanityValue: 40, healthValue: 40, cookingTime: 3, requirements: '2 Units of Dragon Fruit and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Cave Banana Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Cave Banana and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Durian Wine', hungerValue: 35, sanityValue: -40, healthValue: -5, cookingTime: 3, requirements: '2 Units of Durian and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Watermelon Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Watermelon and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Fig Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Fig and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Glow Berry Wine', hungerValue: 40, sanityValue: -10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Glow Berry or Lesser Glow Berry and 1 Unit of Ice.', effects: 'Gives off a healthy glow.', cookingStation: "keg" },
  { name: 'Banana Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Banana and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Coconut Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3, requirements: '2 Units of Halved Coconut and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Pineapple Wine', hungerValue: 25, sanityValue: 20, healthValue: 40, cookingTime: 3, requirements: '2 Units of Halved Pineapple and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Nightberry Wine', hungerValue: 35, sanityValue: 15, healthValue: 0, cookingTime: 3, requirements: '2 Units of Nightberry and 1 Unit of Ice.', effects: 'Grants night vision.', cookingStation: "keg" },
  { name: 'Carrot Juice', hungerValue: 20, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Carrot and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Corn Juice', hungerValue: 25, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Corn and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Eggplant Juice', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Eggplant and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Pumpkin Juice', hungerValue: 30, sanityValue: 10, healthValue: 30, cookingTime: 3, requirements: '2 Units of Pumpkin and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Lichen Juice', hungerValue: 20, sanityValue: -15, healthValue: 30, cookingTime: 3, requirements: '2 Units of Lichen and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Cactus Juice', hungerValue: 40, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Cactus or Cactus Flower and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Garlic Juice', hungerValue: 25, sanityValue: -5, healthValue: 30, cookingTime: 3, requirements: '2 Units of Garlic and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Asparagus Juice', hungerValue: 20, sanityValue: 10, healthValue: 45, cookingTime: 3, requirements: '2 Units of Asparagus and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Onion Juice', hungerValue: 25, sanityValue: -20, healthValue: 40, cookingTime: 3, requirements: '2 Units of Onion and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Toma Root Juice', hungerValue: 25, sanityValue: 10, healthValue: 50, cookingTime: 3, requirements: '2 Units of Toma Root and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Potato Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 30, cookingTime: 3, requirements: '2 Units of Potato and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Pepper Juice', hungerValue: 45, sanityValue: -20, healthValue: 30, cookingTime: 3, requirements: '2 Units of Pepper and 1 Unit of Ice.', effects: 'Warms the body.', cookingStation: "keg" },
  { name: 'Red Cap Juice', hungerValue: 40, sanityValue: 10, healthValue: 30, cookingTime: 3, requirements: '2 Units of Red Cap and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Green Cap Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Green Cap and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Blue Cap Juice', hungerValue: 20, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Blue Cap and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Moon Shroom Juice', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Moon Shroom and 1 Unit of Ice.', effects: 'Wards off sleep.', cookingStation: "keg" },
  { name: 'Kelp Juice', hungerValue: 65, sanityValue: -20, healthValue: 35, cookingTime: 3, requirements: '2 Units of Kelp and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Ripe Stone Fruit Juice', hungerValue: 45, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Ripe Stone Fruit and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Champignon Juice', hungerValue: 62.5, sanityValue: -10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Champignon and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Aloe Juice', hungerValue: 50, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Aloe and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Radish Juice', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Radish and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Sweet Potato Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Sweet Potato and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Lotus Flower Juice', hungerValue: 20, sanityValue: 10, healthValue: 60, cookingTime: 3, requirements: '2 Units of Lotus Flower and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Seaweed Juice', hungerValue: 62.5, sanityValue: -10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Seaweed and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Taro Root Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Taro Root and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Watercress Juice', hungerValue: 20, sanityValue: 10, healthValue: 35, cookingTime: 3, requirements: '2 Units of Watercress and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Sea Cucumber Juice', hungerValue: 30, sanityValue: 10, healthValue: 30, cookingTime: 3, requirements: '2 Units of Sea Cucumber and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Parsnip Juice', hungerValue: 20, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Parsnip and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Turnip Juice', hungerValue: 70, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Turnip and 1 Unit of Ice.', cookingStation: "keg" },
  { name: 'Fennel Juice', hungerValue: 70, sanityValue: -20, healthValue: 35, cookingTime: 3, requirements: '2 Units of Fennel and 1 Unit of Ice.', cookingStation: "keg" },
];
