import { Dish } from './dish.service';

export const GENERAL_DISHES: Dish[] = [
  { name: 'Slaw', hungerValue: 25, sanityValue: 10, healthValue: 20, requirements: '2 Units of Fennel and 1 Unit of Radish.' },
  { name: 'Lotus Chips', hungerValue: 12.5, sanityValue: 50, healthValue: 8, requirements: '3 Units of Lotus Flower.' },
  { name: 'Poi', hungerValue: 62.5, sanityValue: 10, healthValue: 30, requirements: '3 Units of Taro Root. Can\'t have Inedible.' },
  { name: 'Cucumber Salad', hungerValue: 25, sanityValue: 15, healthValue: 10, requirements: '3 Unit of Sea Cucumber and 1 Unit of Veggie. Can\'t have Taro Root.', effects: 'Dissipates moisture.' },
  { name: 'Watercress Soup', hungerValue: 37.5, sanityValue: 5, healthValue: 20, requirements: '2 Units of Watercress, 1 Unit of Succulent and 3 Unit of Veggie.', effects: 'Cools the body.' },
  { name: 'Symphony of the Gears', hungerValue: 150, sanityValue: 150, healthValue: 135, requirements: '2 Units of Gears and 2 Units of Scrap.', effects: 'Only WX-78 Can eat this food.' },
  { name: 'Deadly Feast', hungerValue: 150, sanityValue: -300, healthValue: -100, requirements: '3 Unit of Long Pig and 1 Unit of Bone Shards.', effects: 'Hurts the body.' },
  { name: 'Tigela di\' Merde', hungerValue: 0, sanityValue: 0, healthValue: 0, requirements: '1 Unit of Manure, 1 Unit of Guano, 1 Unit of Glommer\'s Goop and 1 Unit of Salt.' },
  { name: 'Kitty Snack', hungerValue: 25, sanityValue: 15, healthValue: 20, requirements: '1 Unit of Fish, 1 Unit of Flour and 2 Units of Spot Spice.' },
  { name: 'Kitty Kat Snack', hungerValue: 15, sanityValue: 15, healthValue: 60, requirements: '1 Unit of Dairy, 1 Unit of Syrup and 2 Units of Flour.' },
  { name: 'Bowl of Popcorn', hungerValue: 75, sanityValue: 33, healthValue: 5, requirements: '3 Units of Corn and 1 Unit of Salt. Can\'t have Popcorn (Cooked Corn).' },
  { name: 'Fig Juice', hungerValue: 15, sanityValue: 50, healthValue: 0, requirements: '1 Unit of Fig and 2 Units of Ice. Can\'t have Meat, Fish or Inedible.', effects: 'Cools the body.' },
  { name: 'Coconut Water', hungerValue: 0, sanityValue: 0, healthValue: 20, requirements: '1 Unit of Halved Coconut, 2 Units of Ice and 1 Unit of Twigs.', effects: 'Cools the body.' },
  { name: 'Eyespaghetti', hungerValue: 150, sanityValue: -150, healthValue: 150, requirements: '1 Unit of Deerclops Eyeball, 1 Unit of Toma Root and 1 Unit of Flour.', effects: 'Calls the monster. (Configurable).' },
  { name: 'Soul Stew', hungerValue: 62.5, sanityValue: -10, healthValue: 10, requirements: '1 Unit of Soul in a Bottle and 2 Units of Bone Shards.', effects: 'Only Wortox can eat this food and Soul-starve killer.' },
  { name: 'Fortune Cookie', hungerValue: 20, sanityValue: 5, healthValue: 3, requirements: '1 Unit of Flour, 1 Unit of Sweetener and 1 Unit of Papyrus.', effects: 'Tells your fortune.' },
  { name: 'Cornocupia', hungerValue: 75, sanityValue: 25, healthValue: 12, requirements: '1 Unit of Meat, 1 Unit of Veggie, 1 Unit of Fruit and 1 Unit of Beefalo Horn.', effects: 'Everyone can eat and Breaks after eating.' },
  { name: 'Milk Box', hungerValue: 0, sanityValue: 5, healthValue: 25, requirements: '2 Units of Ice and 2 Units of Milk. Can\'t have Milk Box.', effects: 'Is a Crock Pot ingredient.' },
  { name: 'Honey Jar', hungerValue: 45, sanityValue: 5, healthValue: 30, requirements: '1 Unit of Honeycomb and 3 Units of Honey.' },
  { name: 'Cup of Water', hungerValue: 1, sanityValue: 1, healthValue: 1, requirements: '2 Units of Ice. Can\'t have more than 2 Units of Ice.', effects: 'Cleans the body.' },
  { name: 'Crab Artichoke', hungerValue: 12.5, sanityValue: 60, healthValue: 40, requirements: '2 Units of Crab Meat, 1 Unit of Kelp or Seaweed or Watercress and 1 Unit of Spot Spice. Can\'t have Cooked Kelp, Dried Kelp, Cooked Seaweed and Dried Seaweed.' },
  { name: 'Cheese', hungerValue: 25, sanityValue: 5, healthValue: 10, requirements: '2 Units of Milk and 1 Unit of Spot Spice. Can\'t have Meat, Garlic and Koalefant Milk.' },
  { name: 'White Cheese', hungerValue: 25, sanityValue: 20, healthValue: 15, requirements: '2 Units of Milk, 1 Unit of Spot Spice and 1 Unit of Garlic. Can\'t have Meat.' },
  { name: 'Koalefant Cheese', hungerValue: 25, sanityValue: 5, healthValue: 20, requirements: '2 Units of Koalefant Milk and 1 Unit of Spot Spice. Can\'t have Meat, Garlic, Beefalo Milk and Electric Milk.' },
  { name: 'Noxious Froggle Bunwich', hungerValue: 62.5, sanityValue: 10, healthValue: -20, requirements: '1 Unit of Poison Frog Legs and 1 Unit of Veggie. Can\'t have Frog Legs.', effects: 'Gives off a frog arom.' },
  { name: 'Pepper Rolls', hungerValue: 32.5, sanityValue: -15, healthValue: 40, requirements: '2 Units of Pepper, 1 Unit of Flour and 1 Unit of Spot Spice.', effects: 'Warms the body.' },
  { name: 'Chocolate', hungerValue: 12.5, sanityValue: 33, healthValue: -5, requirements: '2 Units of Nuts, 1 Unit of Milk and 1 Unit of Sugar.' },
  { name: 'White Chocolate', hungerValue: 33, sanityValue: 12.5, healthValue: -5, requirements: '2 Units of Nuts, 1 Unit of Beefalo Milk and 1 Unit of Sugar.' },
  { name: 'Tricolor Dango', hungerValue: 12.5, sanityValue: 5, healthValue: 30, requirements: '1 Unit of Milk, 1 Unit of Sugar, 1 Unit of Flour and 1 Unit of Twigs.' },
  { name: 'French Fries', hungerValue: 32.5, sanityValue: 10, healthValue: 30, requirements: '2 Units of Potato, 1 Unit of Oil and 1 Unit of Salt.' },
  { name: 'Onion Rings', hungerValue: 25, sanityValue: 20, healthValue: 15, requirements: '2 Units of Onion, 1 Unit of Flour and 1 Unit of Oil.' },
  { name: 'Donuts', hungerValue: 50, sanityValue: 10, healthValue: -3, requirements: '2 Units of Flour, 1 Unit of Oil and 1 Unit of Sugar.' },
  { name: 'Chocolate Donuts', hungerValue: 55, sanityValue: 40, healthValue: -5, requirements: '1 Unit of Chocolate, 1 Unit of Oil, 1 Unit of Flour and 1 Unit of Sugar.' },
  { name: 'White Chocolate Donuts', hungerValue: 75, sanityValue: 15, healthValue: -5, requirements: '1 Unit of White Chocolate, 1 Unit of Oil, 1 Unit of Flour and 1 Unit of Sugar.' },
  { name: 'Gummy Beargers', hungerValue: 30, sanityValue: -5, healthValue: 5, requirements: '1 Unit of Thick Fur, 1 Unit of Gummy Slug and 2 Units of Sweetener.', effects: 'Calls the monster. (Configurable).' },
  { name: 'Pretzel', hungerValue: 60, sanityValue: 15, healthValue: 40, requirements: '1 Unit of Butter, 1 Unit of Salt and 2 Units of Flour.' },
  { name: 'Elote en Vaso', hungerValue: 50, sanityValue: 50, healthValue: 50, requirements: '1 Unit of Corn, 1 Unit of Pepper, 1 Unit of Salt and 1 Unit of Butter or Cheese.', effects: 'Warms the body.' },
  { name: 'Cotton Candy', hungerValue: 12.5, sanityValue: 33, healthValue: -5, requirements: '3 Units of Sugar and 1 Unit of Twigs.' },
  { name: 'Roasted Hazelnuts', hungerValue: 25, sanityValue: 10, healthValue: 10, requirements: '2 Units of Nuts and 2 Units of Birchnuts.' },
  { name: 'Monster Muffin', hungerValue: 50, sanityValue: -15, healthValue: -10, requirements: '2 Units of Honey, 1 Unit of Flour and 1 Unit of Nightmare Fuel.' },
  { name: 'Pink Cake', hungerValue: 62.5, sanityValue: 20, healthValue: 5, requirements: '2 Units of Sugar, 1 Unit of Flour and 1 Unit of Egg.' },
  { name: 'Potato Chips', hungerValue: 62.5, sanityValue: 5, healthValue: 40, requirements: '2 Units of Potato, 1 Unit of Oil and 1 Unit of Spot Spice.' },
  { name: 'Bread', hungerValue: 12.5, sanityValue: 5, healthValue: 0, requirements: '3 Units of Flour and 1 Unit of Spot Spice.', effects: 'Gives 3 Units when cooked and Is a Crock Pot ingredient.' },
  { name: 'Hot Hound', hungerValue: 32.5, sanityValue: 10, healthValue: 60, requirements: '1 Unit of Bread, 1 Unit of Meat, 1 Unit of Toma Root and 1 Unit of Spot Spice.' },
  { name: 'Milkshake', hungerValue: 12.5, sanityValue: 30, healthValue: 30, requirements: '2 Units of Honey, 1 Unit of Milk and 1 Unit of Berries.', effects: 'Cools the body.' },
  { name: 'Banana Pudding', hungerValue: 12.5, sanityValue: 50, healthValue: 20, requirements: '2 Units of Banana, 1 Unit of Milk and 1 Unit of Sweetener.' },
  { name: 'Seafoam Pudding', hungerValue: 150, sanityValue: 5, healthValue: 60, requirements: '1 Unit of Eel, 1 Unit of Mussel, 1 Unit of Purple Grouper and 1 Unit of Algae.', effects: 'Increases fishing yields.' },
  { name: 'Lollipop', hungerValue: 12.5, sanityValue: 15, healthValue: -3, requirements: '2 Units of Sweetener, 1 Unit of Fruit and 1 Unit of Twigs.' },
  { name: 'Radish Salad', hungerValue: 62.5, sanityValue: 5, healthValue: 15, requirements: '3 Units of Radish and 1 Unit of Spot Spice.' },
  { name: 'Pumpkin Soup', hungerValue: 100, sanityValue: 33, healthValue: 40, requirements: '2 Units of Pumpkin, 1 Unit of Butter and 1 Unit of Spot Spice.' },
  { name: 'Algae Soup', hungerValue: 75, sanityValue: 25, healthValue: 10, requirements: '3 Units of Algae. Can\'t have Meat and Fish.' },
  { name: 'Parsnip Soup', hungerValue: 32.5, sanityValue: 5, healthValue: 15, requirements: '3 Units of Parsnip and 1 Unit of Succulent.', effects: 'Speeds digestion.' },
  { name: 'Living Sandwich', hungerValue: 40, sanityValue: -5, healthValue: 10, requirements: '2 Units of Living Log and 2 Units of Monster Meat.', effects: 'Stimulates the curse.' },
  { name: 'Moon Shroom Sofrito', hungerValue: 18.75, sanityValue: 0, healthValue: 25, requirements: '1 Unit of Carrot, 1 Unit of Moon Shroom and 2 Units of Ripe Stone Fruit.', effects: 'Wards off fear and sleep.' },
  { name: 'Lavender Wobster Soup', hungerValue: 62.5, sanityValue: -5, healthValue: -60, requirements: '1 Unit of Wobster, 1 Unit of Purple Grouper and 1 Unit of Turnip.' },
  { name: 'Wobster Monster', hungerValue: 37.5, sanityValue: -20, healthValue: -60, requirements: '1 Unit of Wobster, 1 Unit of Monster Meat and 2 Units of Veggie.', effects: 'Warms the body.' },
  { name: 'Durian Split', hungerValue: 32.5, sanityValue: -15, healthValue: -5, requirements: '1 Unit of Durian, 1 Unit of Banana, 1 Unit of Ice and 1 Unit of Fruit.', effects: 'Cools the body.' },
  { name: 'Durian Soup', hungerValue: 37.5, sanityValue: 0, healthValue: -15, requirements: '1 Unit of Durian and 3 Units of Veggie.', effects: 'Warms the body.' },
  { name: 'Meated Durians', hungerValue: 37.5, sanityValue: -5, healthValue: -20, requirements: '2 Units of Monster Meat and 2 Units of Durians[/b]' },
  { name: 'Turkey Durian', hungerValue: 45, sanityValue: -30, healthValue: -10, requirements: '1 Unit of Durian, 1 Unit of Cactus Flower and 2 Units of Cactus Flesh. Can\'t have Extra Smelly Durian and Cooked Cactus Flesh.' },
  { name: 'Arachnid Gateau', hungerValue: 37.5, sanityValue: -20, healthValue: -20, requirements: '1 Unit of Spider, 1 Unit of Monster Meat, 1 Unit of Egg and 1 Unit of Flour.' },
  { name: 'Sugar Bombs', hungerValue: 20, sanityValue: 15, healthValue: 5, requirements: '2 Units of Sugar and 2 Units of Wheat.' },
  { name: 'Berries Basket', hungerValue: 18.25, sanityValue: 5, healthValue: 12, requirements: '2 Units of Berries and 1 Unit of Twigs.' },
  { name: 'Onigiris', hungerValue: 20, sanityValue: 8, healthValue: 8, requirements: '2 Units of Rice, 1 Unit of Spot Spice and 1 Unit of Algae.', effects: 'Gives 2 Units when cooked.' },
  { name: 'Omurice', hungerValue: 32.5, sanityValue: 10, healthValue: 30, requirements: '2 Units of Rice, 1 Unit of Egg and 1 Unit of Toma Root.' },
  { name: 'Paella', hungerValue: 50, sanityValue: 10, healthValue: 20, requirements: '1 Unit of Rice, 1 Unit of Mussel, 1 Unit of Spot Spice and 1 Unit of Fish.', effects: 'Warms the body.' },
  { name: 'Tropical Pizza', hungerValue: 75, sanityValue: 15, healthValue: 60, requirements: '1 Unit of Fish, 1 Unit of Flour, 1 Unit of Dairy and 1 Unit of Halved Pineapple or Hot Pineapple.' },
  { name: 'Piña Colada', hungerValue: 25, sanityValue: 10, healthValue: 25, requirements: '1 Unit of Halved Pineapple, 1 Unit of Sweetener and 1 Unit of Ice. Can\'t have Hot Pineapple.', effects: 'Cools the body.' },
  { name: 'Mate', hungerValue: 12.5, sanityValue: 10, healthValue: 5, requirements: '2 Units of Tillweed and 1 Unit of Ice.', effects: 'Warms the body.' },
  { name: 'Gummy Worms', hungerValue: 25, sanityValue: -5, healthValue: 10, requirements: '1 Unit of Nightberry, 1 Unit of Gummy Slug and 1 Unit of Sugar.', effects: 'Grants night vision.' },
  { name: 'S\'mores', hungerValue: 65, sanityValue: 65, healthValue: 15, requirements: '1 Unit of Flour, 1 Unit of Chocolate and 2 Units of Sugar.' },
  { name: 'Ants On a Living Log', hungerValue: 25, sanityValue: 15, healthValue: 15, requirements: '1 Unit of Living Log, 1 Unit of Fig and 2 Units of Nuts.' },
  { name: 'Moon Muffin', hungerValue: 37.5, sanityValue: 20, healthValue: 5, requirements: '1 Unit of Moon Moth and 0.5 Unit of Veggie. Can\'t have Meat.' },
  { name: 'Sugar Muffin', hungerValue: 18.75, sanityValue: 20, healthValue: 20, requirements: '1 Unit of Sugarfly and 0.5 Unit of Veggie. Can\'t have Meat.' },
  { name: 'Eel Tacos', hungerValue: 37.5, sanityValue: 20, healthValue: 5, requirements: '1 Unit of Eel, 1 Unit of Corn and 1 Unit of Lichen.' },
  { name: 'Meat-Toast Waltz', hungerValue: 37.5, sanityValue: 5, healthValue: 30, requirements: '1 Unit of Bread, 1 Unit of Meat, 1 Unit of Toma Root and 1 Unit of Onion.', effects: 'Slightly boosts inspiration.' },
  { name: 'Complete Breakfast', hungerValue: 150, sanityValue: 5, healthValue: 60, requirements: '1 Unit of Bacon and Eggs, 1 Unit of Flour, 1 Unit of Butter and 1 Unit of Syrup.', effects: 'Slightly boosts mightness.' },
  { name: 'Dumplings', hungerValue: 25, sanityValue: 10, healthValue: 15, requirements: '0.5 Unit of Meat, 1 Unit of Flour, 1 Unit of Oil and 1 Unit of Veggie. Can\'t have 1 or more Units of Meat.' },
  { name: 'Chicken Croquet', hungerValue: 32.5, sanityValue: 0, healthValue: 15, requirements: '1 Unit of Drumstick, 1 Unit of Flour, 1 Unit of Oil and 1 Unit of Spot Spice.' },
  { name: 'Crab King Boil', hungerValue: 62.5, sanityValue: 33, healthValue: 40, requirements: '1 Unit of Crab King Meat, 1 Unit of Corn, 1 Unit of Onion and 1 Unit of Spot Spice. Can\'t Have Cooked Corn.', effects: 'Increased damage to crabs.' },
  { name: 'Pie-Napple', hungerValue: 25, sanityValue: 5, healthValue: 40, requirements: '1 Unit of Halved Pineapple. Can\'t Have Meat.' },
  { name: 'Avocado Toast', hungerValue: 37.5, sanityValue: 5, healthValue: 5, requirements: '2 Units of Ripe Stone Fruit and 1 Unit of Bread.' },
  { name: 'Rice Pudding', hungerValue: 15, sanityValue: 33, healthValue: 5, requirements: '2 Units of Rice, 1 Unit of Dairy and 1 Unit of Spot Spice.' },
  { name: 'Shark Nigiri', hungerValue: 40, sanityValue: -10, healthValue: 20, requirements: '1 Unit of Shark Fin and 2 Units of Rice.', effects: 'Increases naughtiness.' },
  { name: 'Breaded Wobster', hungerValue: 50, sanityValue: 10, healthValue: 60, requirements: '1 Unit of Wobster, 1 Unit of Spot Spice, 1 Unit of Flour and 1 Unit of Oil.' },
  { name: 'Purrito', hungerValue: 62.5, sanityValue: -15, healthValue: 20, requirements: '1 Unit of Bean Bugs, 1 Unit of Rice and 1 Unit of Flour.' },
  { name: 'Horchata', hungerValue: 20, sanityValue: 5, healthValue: 40, requirements: '1 Unit of Rice, 1 Unit of Dairy, 1 Unit of Sweetener and 1 Unit of Ice.', effects: 'Cools the body.' },
  { name: 'Wobster Cocktail', hungerValue: 32.5, sanityValue: 60, healthValue: 20, requirements: '1 Unit of Wobster, 1 Unit of Toma Root, 1 Unit of Pepper. Can\'t Have Inedible.', effects: 'Warms the body.' },
  { name: 'Bubblegranate', hungerValue: 12.5, sanityValue: 10, healthValue: 25, requirements: '1 Unit of Pomegranate, 1 Unit of Sweetener and 1 Unit of Ice.', effects: 'Cools the body.' },
  { name: 'Piegranate', hungerValue: 32.5, sanityValue: 20, healthValue: 40, requirements: '1 Unit of Pomegranate, 1 Unit of Flour and 1 Unit of Sweetener.' },
  { name: 'Pineapple Cake', hungerValue: 25, sanityValue: 40, healthValue: 20, requirements: '1 Unit of Halved Pineapple, 1 Unit of Egg, 1 Unit of Flour and 1 Unit of Sweetener.' },
  { name: 'Meat Pasty', hungerValue: 62.5, sanityValue: 5, healthValue: 20, requirements: '1 Unit of Meat, 1 Unit of Flour, 1 Unit of Veggie and 1 Unit of Oil. Can\'t Have Wobster and can\'t have less than 1 Unit of Meat.' },
  { name: 'Cheese Pasty', hungerValue: 37.5, sanityValue: 33, healthValue: 40, requirements: '1 Unit of Cheese, 1 Unit of Flour, 1 Unit of Spot Spice and 1 Unit of Oil.' },
  { name: 'Brigadier', hungerValue: 32.5, sanityValue: 50, healthValue: 25, requirements: '1 Unit of Chocolate, 1 Unit of Sugar and 1 Unit of Nuts.' },
  { name: 'Lasagna', hungerValue: 37.5, sanityValue: 30, healthValue: 30, requirements: '1 Unit of Meat, 1 Unit of Toma Root and 1 Unit of Flour. Can\'t Have Wobster, Monster Food or Spot Spice.' },
  { name: 'FLT', hungerValue: 32.5, sanityValue: 33, healthValue: 15, requirements: '1 Unit of Bright Frog Legs, 1 Unit of Toma Root, 1 Unit of Algae and 1 Unit of Foliage.', effects: 'Increases planar defense' },
  { name: 'Rice and Beans', hungerValue: 62.5, sanityValue: 20, healthValue: 5, requirements: '2 Units of Bean Bugs and 1 Unit of Rice.', effects: 'Warms the body.' },
  { name: 'Jawsbreaker', hungerValue: 12.5, sanityValue: 33, healthValue: -30, requirements: '2 Units of Sweetener, 1 Unit of Shark Fin and 1 Unit of Sugar.', effects: 'Allures ocean creatures.' },
];
