import { Dish } from './dish.service';

export const PRESERVES_DISHES: Dish[] = [
  { name: 'Mayonnaise', hungerValue: 12.5, sanityValue: 15, healthValue: 10, cookingTime: 1, requirements: '1 Unit of Egg, 1 Unit of Oil and 1 Unit of Salt.', effects: 'Restores hunger over time.', cookingStation: "preservesJar", image: "" },
  { name: 'Chicken Mayonnaise', hungerValue: 25, sanityValue: 25, healthValue: 0, cookingTime: 1, requirements: '1 Unit of Chicken Egg, 1 Unit of Oil and 1 Unit of Salt.', effects: 'Restores hunger over time.', cookingStation: "preservesJar", image: "" },
  { name: 'Tallbird Mayonnaise', hungerValue: 12.5, sanityValue: 5, healthValue: 30, cookingTime: 1, requirements: '1 Unit of Tallbird Egg, 1 Unit of Oil and 1 Unit of Salt.', effects: 'Restores hunger over time.', cookingStation: "preservesJar", image: "" },
  { name: 'Void Mayonnaise', hungerValue: 62.5, sanityValue: -5, healthValue: 30, cookingTime: 3, requirements: '1 Unit of Nightmare Fuel,1 Unit of Egg and 1 Unit of Salt.', effects: 'Decreases sanity over time.', cookingStation: "preservesJar", image: "" },
  { name: 'Tartar Sauce', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '1 Unit of Mayonnaise, 1 Unit of Spot Spice and 1 Unit of Sea Cucumber.', effects: 'Restores hunger over time.', cookingStation: "preservesJar", image: "" },
  { name: 'Beefalo Butter', hungerValue: 25, sanityValue: 40, healthValue: 0, cookingTime: 4, requirements: '2 Units of Beefalo Milk and 1 Unit of Salt.', cookingStation: "preservesJar", image: "" },
  { name: 'Koalefant Butter', hungerValue: 25, sanityValue: 20, healthValue: 20, cookingTime: 4, requirements: '2 Units of Koalefant Milk and 1 Unit of Salt.', cookingStation: "preservesJar", image: "" },
  { name: 'Volt Goat Butter', hungerValue: 40, sanityValue: 0, healthValue: 25, cookingTime: 4, requirements: '2 Units of Electric Milk and 1 Unit of Salt.', cookingStation: "preservesJar", image: "" },
  { name: 'Berries Jam', hungerValue: 20, sanityValue: 20, healthValue: 10, cookingTime: 2, requirements: '2 Units of Berries and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Juicy Berries Jam', hungerValue: 20, sanityValue: 20, healthValue: 10, cookingTime: 2, requirements: '2 Units of Juicy Berries and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Pomegranate Jam', hungerValue: 25, sanityValue: 30, healthValue: 10, cookingTime: 2, requirements: '2 Units of Pomegranate and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Dragon Fruit Jam', hungerValue: 40, sanityValue: 40, healthValue: 10, cookingTime: 2, requirements: '2 Units of Dragon Fruit and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Cave Banana Jam', hungerValue: 25, sanityValue: 25, healthValue: 10, cookingTime: 2, requirements: '2 Units of Cave Banana and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Durian Jam', hungerValue: 35, sanityValue: -20, healthValue: -5, cookingTime: 2, requirements: '2 Units of Durian and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Watermelon Jam', hungerValue: 35, sanityValue: 20, healthValue: 10, cookingTime: 2, requirements: '2 Units of Watermelon and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Fig Jam', hungerValue: 25, sanityValue: 20, healthValue: 10, cookingTime: 2, requirements: '2 Units of Fig and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Banana Jam', hungerValue: 20, sanityValue: 33, healthValue: 10, cookingTime: 2, requirements: '2 Units of Banana and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Coconut Jam', hungerValue: 20, sanityValue: 33, healthValue: 10, cookingTime: 2, requirements: '2 Units of Halved Coconut and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Glow Berry Jam', hungerValue: 40, sanityValue: -10, healthValue: 10, cookingTime: 2, requirements: '2 Units of Glow Berry or Lesser Glow Berry and 1 Unit of Sweetener.', effects: 'Gives off a healthy glow.', cookingStation: "preservesJar", image: "" },
  { name: 'Pineapple Jam', hungerValue: 25, sanityValue: 15, healthValue: 33, cookingTime: 2, requirements: '2 Units of Halved Pineapple and 1 Unit of Sweetener.', cookingStation: "preservesJar", image: "" },
  { name: 'Nightberry Jam', hungerValue: 25, sanityValue: 10, healthValue: 0, cookingTime: 2, requirements: '2 Units of Nightberry and 1 Unit Sweetener.', effects: 'Grants night vision.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Carrot', hungerValue: 30, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Carrot and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Corn', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Corn and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Eggplant', hungerValue: 25, sanityValue: 10, healthValue: 35, cookingTime: 3, requirements: '2 Units of Eggplant and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Pumpkin', hungerValue: 20, sanityValue: 10, healthValue: 50, cookingTime: 3, requirements: '2 Units of Pumpkin and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Lichen', hungerValue: 15, sanityValue: -15, healthValue: 30, cookingTime: 3, requirements: '2 Units of Lichen and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Cactus', hungerValue: 25, sanityValue: -10, healthValue: 50, cookingTime: 3, requirements: '2 Units of Cactus or Cactus Flower and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Garlic', hungerValue: 30, sanityValue: -10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Garlic and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Asparagus', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Asparagus and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Onion', hungerValue: 62.5, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Onion and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Toma Root', hungerValue: 62.5, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Toma Root and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Potato', hungerValue: 70, sanityValue: -10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Potato and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Pepper', hungerValue: 25, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Pepper and 1 Unit of Spot Spice.', effects: 'Warms the body.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Red Cap', hungerValue: 62.5, sanityValue: -15, healthValue: 20, cookingTime: 3, requirements: '2 Units of Red Cap and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Green Cap', hungerValue: 50, sanityValue: -10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Green Cap and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Blue Cap', hungerValue: 30, sanityValue: -5, healthValue: 30, cookingTime: 3, requirements: '2 Units of Blue Cap and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Moon Shroom', hungerValue: 25, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Moon Shroom and 1 Unit of Spot Spice.', effects: 'Wards off sleep.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Kelp', hungerValue: 20, sanityValue: -5, healthValue: 25, cookingTime: 3, requirements: '2 Units of Kelp and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Ripe Stone Fruit', hungerValue: 35, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Ripe Stone Fruit and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Champignon', hungerValue: 25, sanityValue: 10, healthValue: 30, cookingTime: 3, requirements: '2 Units of Champignon and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Aloe', hungerValue: 25, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Aloe and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Radish', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Radish and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Sweet Potato', hungerValue: 62.5, sanityValue: 10, healthValue: 25, cookingTime: 3, requirements: '2 Units of Sweet Potato and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Lotus Flower', hungerValue: 33, sanityValue: 10, healthValue: 33, cookingTime: 3, requirements: '2 Units of Lotus Flower and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Seaweed', hungerValue: 62.5, sanityValue: -10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Seaweed and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Taro Root', hungerValue: 20, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Taro Root and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Watercress', hungerValue: 40, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Watercress and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickles', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Sea Cucumber and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Parsnip', hungerValue: 75, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Parsnip and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Turnip', hungerValue: 32.5, sanityValue: 10, healthValue: 40, cookingTime: 3, requirements: '2 Units of Turnip and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Fennel', hungerValue: 40, sanityValue: -15, healthValue: 30, cookingTime: 3, requirements: '2 Units of Fennel and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
  { name: 'Pickled Rice', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3, requirements: '2 Units of Rice and 1 Unit of Spot Spice.', cookingStation: "preservesJar", image: "" },
];
