import { Dish } from './dish.service';

export const GORGE_DISHES: Dish[] = [
  { name: 'Loaf of Bread', hungerValue: 12.5, sanityValue: 0, healthValue: 3, requirements: '3-4 Units of Flour. Can\'t have Spot Spice.', effects: 'Gives 3 Units when cooked and Is a Crock Pot ingredient.' },
  { name: 'Sweet Potato Chips', hungerValue: 75, sanityValue: 15, healthValue: 25, requirements: '2 Units of Sweet Potato, 1 Unit of Oil and 1 Unit of Spot Spice.' },
  { name: 'Vegetable Soup', hungerValue: 25, sanityValue: 10, healthValue: 8, requirements: '1 Unit of Carrot, 1 Unit of Onion, 1 Unit of Corn and 1 Unit of Foliage. Can\'t have Potato.' },
  { name: 'Jelly Sandwich', hungerValue: 37.5, sanityValue: 15, healthValue: 3, requirements: '1 Unit of Bread, 1 Unit of Berries. Can\'t have Inedible, Veggie, Meat or Fish.' },
  { name: 'Fish Stew', hungerValue: 100, sanityValue: 5, healthValue: 20, requirements: '2 Units of Salmon, 1 Unit of Asparagus and 1 Unit of Spot Spice. Can\'t have Bread.' },
  { name: 'Turnip Cake', hungerValue: 37.5, sanityValue: 10, healthValue: 20, requirements: '2 Units of Turnip and 1 Unit of Flour and 1 Unit of Egg. Can\'t have Dairy.' },
  { name: 'Potato Pancakes', hungerValue: 40, sanityValue: 40, healthValue: 40, requirements: '3 Units of Potato and 1 Unit of Flour. Can\'t have Egg or Fish.' },
  { name: 'Potato Soup', hungerValue: 75, sanityValue: 15, healthValue: 60, requirements: '3 Units of Potato and 1 Unit of Succulent.' },
  { name: 'Fishball Skewers', hungerValue: 37.5, sanityValue: 20, healthValue: 25, requirements: '1 Unit of Fish, 1 Unit of Twigs and 1 Unit of Spot Spice.' },
  { name: 'Meat Skewers', hungerValue: 37.5, sanityValue: 5, healthValue: 20, requirements: '2 Units of Bacon Scraps, 1 Unit of Twigs and 1 Unit of Spot Spice.' },
  { name: 'Stone Soup', hungerValue: 25, sanityValue: 5, healthValue: -10, requirements: '1 Unit of Rocks and 1 Unit of Veggie.' },
  { name: 'Croquette', hungerValue: 50, sanityValue: 10, healthValue: 30, requirements: '2 Units of Potato, 1 Unit of Egg and 1 Unit of Flour. Can\'t have Cooked Potato.' },
  { name: 'Roast Vegetables', hungerValue: 40, sanityValue: 20, healthValue: 25, requirements: '1 Unit of Cooked Onion, 1 Unit of Cooked Asparagus, 1 Unit of Cooked Garlic and 1 Unit of Cooked Carrot.' },
  { name: 'Meatloaf', hungerValue: 25, sanityValue: 5, healthValue: 30, requirements: '2 Units of Bacon Scraps, 1 Unit of Flour and 1 Unit of Veggie. Can\'t have Foliage.' },
  { name: 'Carrot Soup', hungerValue: 37.5, sanityValue: 10, healthValue: 10, requirements: '3 Units of Carrot and 1 Unit of Spot Spice.' },
  { name: 'Fish Pie', hungerValue: 62.5, sanityValue: 5, healthValue: 40, requirements: '1 Unit of Salmon, 1 Unit of Flour and 1 Unit of Veggie. Can\'t have Bread.' },
  { name: 'Fish and Chips', hungerValue: 85, sanityValue: 15, healthValue: 50, requirements: '1 Unit of Fish, 1 Unit of Flour and 2 Units of Potato.' },
  { name: 'Meat Pie', hungerValue: 50, sanityValue: 25, healthValue: 3, requirements: '1 Unit of Meat, 2 Units of Flour and 1 Unit of Veggie. Can\'t have Potato, Onion or Bacon Scraps.' },
  { name: 'Sliders', hungerValue: 12.5, sanityValue: 25, healthValue: 5, requirements: '2 Units of Bacon Scraps, 1 Unit of Bread and 1 Unit of Foliage. Can\'t have Loaf of Bread.' },
  { name: 'Jelly Roll', hungerValue: 25, sanityValue: 15, healthValue: 8, requirements: '3 Units of Berries and 1 Unit of Flour.' },
  { name: 'Carrot Cake', hungerValue: 37.5, sanityValue: 5, healthValue: 15, requirements: '2 Units of Carrot, 1 Unit of Flour and 1 Unit of Egg. Can\'t have Cooked Carrot.' },
  { name: 'Garlic Mashed Potatoes', hungerValue: 37.5, sanityValue: 15, healthValue: 30, requirements: '2 Units of Garlic, 1 Unit of Potato and 1 Unit of Spot Spice.' },
  { name: 'Garlic Bread', hungerValue: 37.5, sanityValue: 5, healthValue: 30, requirements: '1 Unit of Bread and 2 Units of Garlic. Can\'t have Meat or Fish.' },
  { name: 'Tomato Soup', hungerValue: 50, sanityValue: 15, healthValue: 25, requirements: '3 Units of Toma Roots and 1 Unit of Spot Spice.' },
  { name: 'Sausage', hungerValue: 37.5, sanityValue: 10, healthValue: 30, requirements: '3 Units of Bacon Scraps and 1 Unit of Spot Spice.' },
  { name: 'Candied Fish', hungerValue: 25, sanityValue: 60, healthValue: 5, requirements: '1 Unit of Salmon and 1 Unit of Syrup.' },
  { name: 'Stuffed Mushroom', hungerValue: 20, sanityValue: 10, healthValue: 15, requirements: '3 Units of Champignon. Can\'t have Foliage, Succulent or Dairy.' },
  { name: 'Bruschetta', hungerValue: 62.5, sanityValue: 10, healthValue: 50, requirements: '1 Unit of Bread, 1 Unit of Spot Spice and 2 Units of Toma Roots.' },
  { name: 'Hamburger', hungerValue: 80, sanityValue: 5, healthValue: 5, requirements: '1 Unit of Bread, 1 Unit of Meat, 1 Unit of Bacon Scraps and 1 Unit of Foliage. Can\'t have Fish.' },
  { name: 'Fishburger', hungerValue: 80, sanityValue: 5, healthValue: 20, requirements: '1 Unit of Bread, 1 Unit of Salmon and 1 Unit of Foliage.' },
  { name: 'Mushroom Burger', hungerValue: 80, sanityValue: 0, healthValue: 5, requirements: '1 Unit of Bread, 2 Units of Champignon and 1 Unit of Foliage.' },
  { name: 'Fish Steak', hungerValue: 150, sanityValue: 15, healthValue: 15, requirements: '1 Unit of Cooked Salmon, 1 Unit of Foliage and 1 Unit of Spot Spice. Can\'t have Raw Salmon.' },
  { name: 'Curry', hungerValue: 75, sanityValue: 15, healthValue: 10, requirements: '1 Unit of Meat, 1 Unit of Veggie and 2 Units of Spot Spice.' },
  { name: 'Spaghetti and Meatball', hungerValue: 80, sanityValue: 25, healthValue: 8, requirements: '1 Unit of Meat, 1 Unit of Flour, 1 Unit of Spot Spice and 1 Unit of Toma Root.' },
  { name: 'Poached Fish', hungerValue: 25, sanityValue: 25, healthValue: 40, requirements: '1 Unit of Salmon, 2 Units of Foliage and 1 Unit of Spot Spice.' },
  { name: 'Shepherd\'s Pie', hungerValue: 150, sanityValue: 10, healthValue: 20, requirements: '1 Unit of Meat, 1 Unit of Onion, 1 Unit of Garlic and 1 Unit of Spot Spice.' },
  { name: 'Caramel Candy', hungerValue: 20, sanityValue: 33, healthValue: 0, requirements: '1 Unit of Syrup and 4 Units of Sweetener.', effects: 'Speeds the hands.' },
  { name: 'Bread Pudding', hungerValue: 40, sanityValue: 40, healthValue: 15, requirements: '1 Unit of Berries, 2 Units of Flour and 1 Unit of Syrup.' },
  { name: 'Berry Tart', hungerValue: 20, sanityValue: 15, healthValue: 25, requirements: '2 Units of Berries, 1 Unit of Flour and 1 Unit of Sweetener. Can\'t have Syrup.' },
  { name: 'Macaroni and Cheese', hungerValue: 37.5, sanityValue: 50, healthValue: 20, requirements: '2 Units of Flour and 1 Unit of Milk. Can\'t have Fish, Meat, Bread, Fruit or Syrup.' },
  { name: 'Bagel and Fish', hungerValue: 75, sanityValue: 50, healthValue: 50, requirements: '1 Unit of Bread, 1 Unit of Milk, 1 Unit of Salmon and 1 Unit of Spot Spice.' },
  { name: 'Grilled Cheese', hungerValue: 50, sanityValue: 40, healthValue: 60, requirements: '1 Unit of Dairy or Cheese and 1 Unit of Bread. Can\'t have Fish, Meat or Spot Spice. Can\'t have more than 1 Unit of Inedible.' },
  { name: 'Cream of Mushroom Soup', hungerValue: 50, sanityValue: 25, healthValue: 30, requirements: '1 Unit of Milk, 2 Units of Champignon and 1 Unit of Succulent.' },
  { name: 'Manicotti', hungerValue: 50, sanityValue: 50, healthValue: 8, requirements: '1 Unit of Flour, 1 Unit of Milk, 1 Unit of Spot Spice and 1 Unit of Toma Root.' },
  { name: 'Creamy Fettuccine', hungerValue: 50, sanityValue: 40, healthValue: 20, requirements: '1 Unit of Flour, 1 Unit of Garlic, 1 Unit of Succulent and 1 Unit of Dairy.' },
  { name: 'Onion Soup', hungerValue: 75, sanityValue: -5, healthValue: 25, requirements: '1 Unit of Flour, 1 Unit of Dairy and 2 Units of Onion.' },
  { name: 'Bread Cutlet', hungerValue: 75, sanityValue: 15, healthValue: 30, requirements: '2 Units of Meat and 2 Units of Flour. Can\'t have more than 1 Unit of Monster Food.' },
  { name: 'Creamy Fish', hungerValue: 75, sanityValue: 30, healthValue: 40, requirements: '1 Unit of Milk, 1 Unit of Veggie, 1 Unit of Salmon and 1 Unit of Spot Spice.' },
  { name: 'Pot Roast', hungerValue: 150, sanityValue: 5, healthValue: 30, requirements: '2 Units of Meat, 1 Unit of Veggie and 1 Unit of Spot Spice. Can\'t have Fish.' },
  { name: 'Crab Cake', hungerValue: 62.5, sanityValue: 20, healthValue: 60, requirements: '1 Unit of Crab Meat, 1 Unit of Succulent, 1 Unit of Flour and 1 Unit of Spot Spice.' },
  { name: 'Steak Frites', hungerValue: 100, sanityValue: 5, healthValue: 40, requirements: '2 Units of Meat and 2 Units of Potato.' },
  { name: 'Shooter Sandwich', hungerValue: 100, sanityValue: 15, healthValue: 5, requirements: '1 Unit of Meat, 1 Unit of Bread and 1 Unit of Spot Spice. Can\'t have Fish and Toma Root.' },
  { name: 'Bacon Wrapped Meat', hungerValue: 50, sanityValue: 0, healthValue: 10, requirements: '1 Unit of Meat and 2 Units of Bacon Scraps. Can\'t have Inedible or Bread.' },
  { name: 'Crab Roll', hungerValue: 75, sanityValue: 25, healthValue: 60, requirements: '1 Unit of Crab Meat, 1 Unit of Foliage, 1 Unit of Champignon and 1 Unit of Flour.' },
  { name: 'Crab Ravioli', hungerValue: 40, sanityValue: 50, healthValue: 60, requirements: '1 Unit of Crab Meat, 1 Unit of Flour, 1 Unit of Dairy and 1 Unit of Veggie.' },
  { name: 'Caramel Cube', hungerValue: 20, sanityValue: 100, healthValue: -10, requirements: '2 Units of Syrup and 2 Units of Dairy.', effects: 'Kyno\'s favourite dish.' },
  { name: 'Scone', hungerValue: 37.5, sanityValue: 40, healthValue: 5, requirements: '1 Unit of Fruit, 2 Units of Flour and 1 Unit of Dairy.' },
  { name: 'Cheesecake', hungerValue: 75, sanityValue: 60, healthValue: 20, requirements: '2 Units of Berries, 1 Unit of Flour and 1 Unit of Dairy.' },
  { name: 'Syrup', hungerValue: 9.375, sanityValue: 0, healthValue: 3, requirements: '3-4 Units of Sap and 1 Unit of Dairy or Sweetener. Can\'t have Monster Food.', effects: 'Gives 3 Units if cooked on Elder\'s Pot.' },
];
