import { Dish } from './dish.service';

export const WARLY_DISHES: Dish[] = [
  { name: 'Mussel Bouillabaise', hungerValue: 37.5, sanityValue: 15, healthValue: 60, requirements: '3 Units of Mussel and 1 Unit of Veggie. Can\'t have Cooked Mussel.' },
  { name: 'Sweet Potato Soufflé', hungerValue: 50, sanityValue: 15, healthValue: 20, requirements: '2 Units of Sweet Potato and 2 Units of Egg. Can\'t have Cooked Sweet Potato.' },
  { name: 'Bubble Tea', hungerValue: 12.5, sanityValue: 33, healthValue: 20, requirements: '1 Unit of Piko, 1 Unit of Tea Leaves, 1 Unit of Sweetener and 1 Unit of Ice.', effects: 'Wards off sleep.' },
  { name: 'French Onion Soup', hungerValue: 37.5, sanityValue: 5, healthValue: 40, requirements: '2 Units of Onion, 3 Units of Veggie and 1 Unit of Foliage.' },
  { name: 'Mint Jellybeans', hungerValue: 0, sanityValue: 5, healthValue: 2, requirements: '1 Unit of Royal Jelly and 3 Units of Green Cap.', effects: 'Restores sanity over time and Gives 3 Units when cooked.' },
  { name: 'Creamy Jellybeans', hungerValue: 5, sanityValue: 0, healthValue: 2, requirements: '1 Unit of Royal Jelly, 1 Unit of Butter and 1 Unit of Sweetener. Can\'t have Inedible or Monster Food.', effects: 'Restores hunger over time and Gives 3 Units when cooked.' },
  { name: 'Lusty Jellybeans', hungerValue: 2, sanityValue: 2, healthValue: 2, requirements: '2 Units of Royal Jelly, 1 Unit of Dragon Fruit and 1 Unit of Pomegranate.', effects: 'Restores all over time and Gives 3 Units when cooked.' },
  { name: 'Super Meaty Stew', hungerValue: 200, sanityValue: 10, healthValue: 15, requirements: '3 Units of Meat and 1 Unit of Spot Spice. Can\'t have more than 1 Unit of Monster Food.' },
  { name: 'Cheeseburger', hungerValue: 100, sanityValue: 30, healthValue: 50, requirements: '1 Unit of Bread, 1 Unit of Meat, 1 Unit of Dairy and 1 Unit of Foliage.' },
  { name: 'Pizza', hungerValue: 150, sanityValue: 20, healthValue: 40, requirements: '1 Unit of Meat, 1 Unit of Flour, 1 Unit of Dairy and 1 Unit of Toma Root.' },
  { name: 'Meat Wellington', hungerValue: 150, sanityValue: 10, healthValue: 20, requirements: '2 Units of Meat, 1 Unit of Bread and 1 Unit of Veggie. Can\'t have more than 1 Unit of Monster Food.' },
  { name: 'Trifle', hungerValue: 37.5, sanityValue: 60, healthValue: 15, requirements: '1 Unit of Fruit, 1 Unit of Flour and 2 Units of Dairy.' },
  { name: 'Sundae', hungerValue: 8, sanityValue: 60, healthValue: 20, requirements: '1 Unit of Berries, 1 Unit of Dairy, 1 Unit of Syrup and 1 Unit of Ice.', effects: 'Cools the body and makes you less susceptible to Overheat.' },
  { name: 'Cinnamon Roll', hungerValue: 50, sanityValue: 20, healthValue: 80, requirements: '1 Unit of Flour, 1 Unit of Syrup, 1 Unit of Spot Spice and 1 Unit of Butter.' },
  { name: 'Prismatic Punch', hungerValue: 12.5, sanityValue: 60, healthValue: 60, requirements: '2 Units of Syrup, 1 Unit of Milk and 1 Unit of Berries.', effects: 'Cools the body.' },
  { name: 'Nachos', hungerValue: 32.5, sanityValue: 10, healthValue: 40, requirements: '1 Unit of Cheese, 1 Unit of Oil, 1 Unit of Spot Spice and 1 Unit of Corn. Can\'t have Cooked Corn.' },
  { name: 'Tom Kha Soup', hungerValue: 40, sanityValue: 33, healthValue: 5, requirements: '1 Unit of Halved Coconut, 1 Unit of Pepper, 1 Unit of Mushroom and 1 Unit of Succulent.', effects: 'Warms the body and makes you susceptible to Freezing.' },
  { name: 'Risotto', hungerValue: 75, sanityValue: 25, healthValue: 33, requirements: '2 Units of Rice, 1 Unit of Champignon and 1 Unit of Dairy.' },
  { name: 'Steak Stir Fry', hungerValue: 62.5, sanityValue: 15, healthValue: -5, requirements: '1 Unit of Meat, 1 Unit of Pepper, 1 Unit of Garlic and 1 Unit of Spot Spice.', effects: 'Warms the body.' },
  { name: 'Glacé Thé de Maman', hungerValue: 12.5, sanityValue: 5, healthValue: 20, requirements: '1 Unit of Orange Piko, 1 Unit of Tea Leaves, 1 Unit of Sweetener and 1 Unit of Ice.', effects: 'Cools the body.' },
  { name: 'Thé de Maman', hungerValue: 25, sanityValue: 10, healthValue: 40, requirements: '1 Unit of Orange Piko, 1 Unit of Tea Leaves and 1 Unit of Sweetener. Can\'t have Ice.', effects: 'Warms the body and Decreases sanity loss.' },
  { name: 'The Lazy Dessert', hungerValue: 12.5, sanityValue: 0, healthValue: -30, requirements: '1 Unit of Desert Stone, 1 Unit of Rocks and 1 Unit of Sweetener.', effects: 'Satisfies the monster.' },
  { name: 'Lava Boiled Egg', hungerValue: 100, sanityValue: 15, healthValue: 60, requirements: '1 Unit of Lavae Egg, 1 Unit of Pepper and 1 Unit of Fire Nettles. Can\'t Have Ice.', effects: 'Warms the body and Grants fire immunity.' },
  { name: 'Tirameesu', hungerValue: 32.5, sanityValue: 15, healthValue: 20, requirements: '1 Unit of Roasted Coffee Beans, 1 Unit of Chocolate and 1 Unit of Dairy. Can\'t Have Coffee Beans.', effects: 'Speeds the body and Dissipates moisture.' },
];
