import { Dish } from './dish.service';

export const PRESERVES_DISHES: Dish[] = [
  { name: 'Mayonnaise', hungerValue: 12.5, sanityValue: 15, healthValue: 10, cookingTime: 1 },
  { name: 'Chicken Mayonnaise', hungerValue: 25, sanityValue: 25, healthValue: 0, cookingTime: 1 },
  { name: 'Tallbird Mayonnaise', hungerValue: 12.5, sanityValue: 5, healthValue: 30, cookingTime: 1 },
  { name: 'Void Mayonnaise', hungerValue: 62.5, sanityValue: -5, healthValue: 30, cookingTime: 3 },
  { name: 'Tartar Sauce', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Beefalo Butter', hungerValue: 25, sanityValue: 40, healthValue: 0, cookingTime: 4 },
  { name: 'Koalefant Butter', hungerValue: 25, sanityValue: 20, healthValue: 20, cookingTime: 4 },
  { name: 'Volt Goat Butter', hungerValue: 40, sanityValue: 0, healthValue: 25, cookingTime: 4 },
  { name: 'Berries Jam', hungerValue: 20, sanityValue: 20, healthValue: 10, cookingTime: 2 },
  { name: 'Juicy Berries Jam', hungerValue: 20, sanityValue: 20, healthValue: 10, cookingTime: 2 },
  { name: 'Pomegranate Jam', hungerValue: 25, sanityValue: 30, healthValue: 10, cookingTime: 2 },
  { name: 'Dragon Fruit Jam', hungerValue: 40, sanityValue: 40, healthValue: 10, cookingTime: 2 },
  { name: 'Cave Banana Jam', hungerValue: 25, sanityValue: 25, healthValue: 10, cookingTime: 2 },
  { name: 'Durian Jam', hungerValue: 35, sanityValue: -20, healthValue: -5, cookingTime: 2 },
  { name: 'Watermelon Jam', hungerValue: 35, sanityValue: 20, healthValue: 10, cookingTime: 2 },
  { name: 'Fig Jam', hungerValue: 25, sanityValue: 20, healthValue: 10, cookingTime: 2 },
  { name: 'Banana Jam', hungerValue: 20, sanityValue: 33, healthValue: 10, cookingTime: 2 },
  { name: 'Coconut Jam', hungerValue: 20, sanityValue: 33, healthValue: 10, cookingTime: 2 },
  { name: 'Glow Berry Jam', hungerValue: 40, sanityValue: -10, healthValue: 10, cookingTime: 2 },
  { name: 'Pineapple Jam', hungerValue: 25, sanityValue: 15, healthValue: 33, cookingTime: 2 },
  { name: 'Nightberry Jam', hungerValue: 25, sanityValue: 10, healthValue: 0, cookingTime: 2 },
  { name: 'Pickled Carrot', hungerValue: 30, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Corn', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Pickled Eggplant', hungerValue: 25, sanityValue: 10, healthValue: 35, cookingTime: 3 },
  { name: 'Pickled Pumpkin', hungerValue: 20, sanityValue: 10, healthValue: 50, cookingTime: 3 },
  { name: 'Pickled Lichen', hungerValue: 15, sanityValue: -15, healthValue: 30, cookingTime: 3 },
  { name: 'Pickled Cactus', hungerValue: 25, sanityValue: -10, healthValue: 50, cookingTime: 3 },
  { name: 'Pickled Garlic', hungerValue: 30, sanityValue: -10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Asparagus', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Onion', hungerValue: 62.5, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Pickled Toma Root', hungerValue: 62.5, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Pickled Potato', hungerValue: 70, sanityValue: -10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Pepper', hungerValue: 25, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Pickled Red Cap', hungerValue: 62.5, sanityValue: -15, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Green Cap', hungerValue: 50, sanityValue: -10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Blue Cap', hungerValue: 30, sanityValue: -5, healthValue: 30, cookingTime: 3 },
  { name: 'Pickled Moon Shroom', hungerValue: 25, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Pickled Kelp', hungerValue: 20, sanityValue: -5, healthValue: 25, cookingTime: 3 },
  { name: 'Pickled Ripe Stone Fruit', hungerValue: 35, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Champignon', hungerValue: 25, sanityValue: 10, healthValue: 30, cookingTime: 3 },
  { name: 'Pickled Aloe', hungerValue: 25, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Radish', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Sweet Potato', hungerValue: 62.5, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Pickled Lotus Flower', hungerValue: 33, sanityValue: 10, healthValue: 33, cookingTime: 3 },
  { name: 'Pickled Seaweed', hungerValue: 62.5, sanityValue: -10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Taro Root', hungerValue: 20, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Pickled Watercress', hungerValue: 40, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickles', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Parsnip', hungerValue: 75, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Pickled Turnip', hungerValue: 32.5, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Pickled Fennel', hungerValue: 40, sanityValue: -15, healthValue: 30, cookingTime: 3 },
  { name: 'Pickled Rice', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3 }
];
