import { Dish } from './dish.service';

export const KEG_DISHES: Dish[] = [
  { name: 'Beer', hungerValue: 12.5, sanityValue: -10, healthValue: 5, cookingTime: 1 },
  { name: 'Pale Ale', hungerValue: 25, sanityValue: -10, healthValue: 15, cookingTime: 2 },
  { name: 'Green Tea', hungerValue: 32, sanityValue: 1, healthValue: 12, cookingTime: 1 },
  { name: 'Black Tea', hungerValue: 32, sanityValue: 12, healthValue: 1, cookingTime: 1 },
  { name: 'Mead', hungerValue: 70, sanityValue: 40, healthValue: -10, cookingTime: 3 },
  { name: "Pirate's Rum", hungerValue: 60, sanityValue: -33, healthValue: -15, cookingTime: 2 },
  { name: 'Twisted Tequila', hungerValue: 32.5, sanityValue: -30, healthValue: 15, cookingTime: 1 },
  { name: 'Nuka-Cola', hungerValue: 12.5, sanityValue: 60, healthValue: -5, cookingTime: 2 },
  { name: 'Nuka-Cola Quantum', hungerValue: 20, sanityValue: 60, healthValue: -10, cookingTime: 3 },
  { name: 'Nukashine', hungerValue: 150, sanityValue: -100, healthValue: 100, cookingTime: 3 },
  { name: 'Sake', hungerValue: 32.5, sanityValue: 20, healthValue: -10, cookingTime: 2 },
  { name: 'Mocha', hungerValue: 33, sanityValue: 33, healthValue: -10, cookingTime: 3 },
  { name: 'Croak-Cola', hungerValue: 12.5, sanityValue: 80, healthValue: -30, cookingTime: 3 },
  { name: 'Tepache', hungerValue: 12.5, sanityValue: 33, healthValue: 20, cookingTime: 1 },
  { name: 'Enlightened Tequila', hungerValue: 12.5, sanityValue: 100, healthValue: 5, cookingTime: 3 },
  { name: 'Sneakmosa', hungerValue: 12.5, sanityValue: -100, healthValue: 5, cookingTime: 3 },
  { name: 'Berries Wine', hungerValue: 20, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Juicy Berries Wine', hungerValue: 20, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Pomegranate Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Dragon Fruit Wine', hungerValue: 20, sanityValue: 40, healthValue: 40, cookingTime: 3 },
  { name: 'Cave Banana Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Durian Wine', hungerValue: 35, sanityValue: -40, healthValue: -5, cookingTime: 3 },
  { name: 'Watermelon Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Fig Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Glow Berry Wine', hungerValue: 40, sanityValue: -10, healthValue: 20, cookingTime: 3 },
  { name: 'Banana Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Coconut Wine', hungerValue: 25, sanityValue: 40, healthValue: 10, cookingTime: 3 },
  { name: 'Pineapple Wine', hungerValue: 25, sanityValue: 20, healthValue: 40, cookingTime: 3 },
  { name: 'Nightberry Wine', hungerValue: 35, sanityValue: 15, healthValue: 0, cookingTime: 3 },
  { name: 'Carrot Juice', hungerValue: 20, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Corn Juice', hungerValue: 25, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Eggplant Juice', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Pumpkin Juice', hungerValue: 30, sanityValue: 10, healthValue: 30, cookingTime: 3 },
  { name: 'Lichen Juice', hungerValue: 20, sanityValue: -15, healthValue: 30, cookingTime: 3 },
  { name: 'Cactus Juice', hungerValue: 40, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Garlic Juice', hungerValue: 25, sanityValue: -5, healthValue: 30, cookingTime: 3 },
  { name: 'Asparagus Juice', hungerValue: 20, sanityValue: 10, healthValue: 45, cookingTime: 3 },
  { name: 'Onion Juice', hungerValue: 25, sanityValue: -20, healthValue: 40, cookingTime: 3 },
  { name: 'Toma Root Juice', hungerValue: 25, sanityValue: 10, healthValue: 50, cookingTime: 3 },
  { name: 'Potato Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 30, cookingTime: 3 },
  { name: 'Pepper Juice', hungerValue: 45, sanityValue: -20, healthValue: 30, cookingTime: 3 },
  { name: 'Red Cap Juice', hungerValue: 40, sanityValue: 10, healthValue: 30, cookingTime: 3 },
  { name: 'Green Cap Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Blue Cap Juice', hungerValue: 20, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Moon Shroom Juice', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Kelp Juice', hungerValue: 65, sanityValue: -20, healthValue: 35, cookingTime: 3 },
  { name: 'Ripe Stone Fruit Juice', hungerValue: 45, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Champignon Juice', hungerValue: 62.5, sanityValue: -10, healthValue: 25, cookingTime: 3 },
  { name: 'Aloe Juice', hungerValue: 50, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Radish Juice', hungerValue: 35, sanityValue: 10, healthValue: 25, cookingTime: 3 },
  { name: 'Sweet Potato Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Lotus Flower Juice', hungerValue: 20, sanityValue: 10, healthValue: 60, cookingTime: 3 },
  { name: 'Seaweed Juice', hungerValue: 62.5, sanityValue: -10, healthValue: 20, cookingTime: 3 },
  { name: 'Taro Root Juice', hungerValue: 62.5, sanityValue: 10, healthValue: 40, cookingTime: 3 },
  { name: 'Watercress Juice', hungerValue: 20, sanityValue: 10, healthValue: 35, cookingTime: 3 },
  { name: 'Sea Cucumber Juice', hungerValue: 30, sanityValue: 10, healthValue: 30, cookingTime: 3 },
  { name: 'Parsnip Juice', hungerValue: 20, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Turnip Juice', hungerValue: 70, sanityValue: 10, healthValue: 20, cookingTime: 3 },
  { name: 'Fennel Juice', hungerValue: 70, sanityValue: -20, healthValue: 35, cookingTime: 3 }
];
